import drone7
import time


drone = drone7.drone("udp:127.0.0.1:14551")

drone.arm_disarm("1")
time.sleep(1)
drone.mode("GUIDED")
time.sleep(1)
drone.takeoff(10)

drone.upload_mission("direk1.txt")
drone.mode("AUTO")
drone.ach_route(2)
time.sleep(2)
drone.mode("GUIDED")
drone.upload_mission("rota1.txt")
time.sleep(1)
drone.mode("AUTO")
drone.ach_image(5,20,"red")
time.sleep(2)
drone.mode("GUIDED")
drone.aim(15,"blue")
drone.land_to_alt(6.5)
drone.aim(15,"blue")
drone.land_control(2.4)
#drone.mek.pump()
drone.upload_mission("rota2.txt")
time.sleep(1)
drone.mode("AUTO")
drone.ach_route(3)
time.sleep(2)
drone.mode("GUIDED")
drone.upload_mission("rota3.txt")
time.sleep(1)
drone.mode("AUTO")
drone.ach_route(3)
time.sleep(2)
drone.mode("GUIDED")
drone.aim(15,"red")
drone.land_to_alt(6.5)
drone.aim(15,"blue")
#drone.mek.openn()
drone.upload_mission("rota4.txt")
time.sleep(1)
drone.mode("AUTO")
drone.ach_route(4)
time.sleep(2)
drone.mode("LAND")


